### ISSUE TITLE
Client seems not to use System Properties proxy définition

### ISSUE THREAD

**Issue by cmarchand** [AxelCourt/saxon-marklogic-ext#10]
When system properties for proxy are defined (e.g. `https.proxySet=true https.proxyHost=fr000-proxy001 https.proxyPort=8080 http.proxySet=true http.proxyHost=fr000-proxy001 httpProxyPort=8080`), the client do not use them, and connects directly without using the proxy.
It is not a problem for me at this point, but it's a reminder...

**Comment by AxelCourt** [comment]
Should be fixed in **version 1.2-RC3**, available for test.
