### ISSUE TITLE
QueryConfigurationFactory.java should indicate which parameter is invalid

### ISSUE THREAD

**Issue by cmarchand** [AxelCourt/saxon-marklogic-ext#3]
QueryConfigurationFactory.java catches ClassCastException & XPathException, and wraps it in a new XPathException.
When supplying a parameter which is not properly datatyped, we only have a message that do not indicates **which** parameter is invalid.

It'll be a great enhancement if we could know which parameter is invalid.

Thanks in advance

**Comment by AxelCourt** [comment]
Hi @cmarchand,

Sorry, I must have missed the notification on this issue, I've just seen it!
Anyway, your problem should be fixed starting with release 1.0.7-98.
I encourage you to use release **1.1.0** though (which fixes issue #4).
