### ISSUE TITLE
The marklogic-client-api version may be a tad old

### ISSUE THREAD

**Issue by gmaricha** [AxelCourt/saxon-marklogic-ext#4]
Hi Axel,

I use _saxon-marklogic-ext_ version 1.0.6-98.
When querying MarkLogic using saxon-marklogic-ext's function _marklogic-query-uri_, I get the following errors in the log  :

> 2018-12-05 15:27:35,333 [Finalizer] INFO  com.marklogic.client.impl.DatabaseClientImpl  - Releasing connection
> déc. 05, 2018 3:27:35 **PM org.jvnet.mimepull.WeakDataFile close**
> **INFOS: File C:\Users\Gilles\AppData\Local\Temp\MIME8688105167904998927.tmp was not deleted**
> 2018-12-05 15:27:35,339 [Finalizer] INFO  com.marklogic.client.impl.DatabaseClientImpl  - Releasing connection
> déc. 05, 2018 3:27:35 PM org.jvnet.mimepull.WeakDataFile close
> INFOS: File C:\Users\Gilles\AppData\Local\Temp\MIME276279067529963830.tmp was not deleted
> déc. 05, 2018 3:27:35 PM org.jvnet.mimepull.WeakDataFile close
> INFOS: File C:\Users\Gilles\AppData\Local\Temp\MIME7093284410616295974.tmp was not deleted
> 2018-12-05 15:27:35,346 [Finalizer] INFO  com.marklogic.client.impl.DatabaseClientImpl  - Releasing connection
> déc. 05, 2018 3:27:35 PM org.jvnet.mimepull.WeakDataFile close
> INFOS: File C:\Users\Gilles\AppData\Local\Temp\MIME4520442507467679602.tmp was not deleted
> 2018-12-05 15:27:35,382 [Finalizer] INFO  com.marklogic.client.impl.DatabaseClientImpl  - Releasing connection
> 2018-12-05 15:27:35,384 [Finalizer] INFO  com.marklogic.client.impl.DatabaseClientImpl  - Releasing connection
> 2018-12-05 15:27:35,385 [Finalizer] INFO  com.marklogic.client.impl.DatabaseClientImpl  - Releasing connection
> 2018-12-05 15:27:35,385 [Finalizer] INFO  com.marklogic.client.impl.DatabaseClientImpl  - Releasing connection
> 2018-12-05 15:27:35,385 [Finalizer] INFO  com.marklogic.client.impl.DatabaseClientImpl  - Releasing connection
> 2018-12-05 15:27:35,387 [Finalizer] INFO  com.marklogic.client.impl.DatabaseClientImpl  - Releasing connection
> déc. 05, 2018 3:27:35 PM org.jvnet.mimepull.WeakDataFile close
> INFOS: File C:\Users\Gilles\AppData\Local\Temp\MIME5109029460070878812.tmp was not deleted
> 2018-12-05 15:27:35,389 [Finalizer] INFO  com.marklogic.client.impl.DatabaseClientImpl  - Releasing connection
> déc. 05, 2018 3:27:35 PM org.jvnet.mimepull.WeakDataFile close
> INFOS: File C:\Users\Gilles\AppData\Local\Temp\MIME8855626960210358780.tmp was not deleted

Dependency analysis  shows that saxon-marklogic-ext depends on _marklogic-client-api_ version 4.0.1 which in turn depends on **mimepull 1.9.4**.
marklogic-client-api version 4.0.2 does not have this dependency, and current version (4.1.1) has neither.
So it may be time to update in the .pom file the marklogic-client-api version.

Regards,
              Gilles

**Comment by AxelCourt** [comment]
Hi @gmaricha,

I've switched to marklogic-client-api 4.1.1.
Unit tests are OK, so it should work just fine!

You can use version **1.1.0** of the plugin. Just let me know if you find bugs!
I've also dropped support for Saxon 9.7 starting with this version.
