### ISSUE TITLE
Saxon light integration

### ISSUE THREAD

**Issue by Marc95** [AxelCourt/saxon-marklogic-ext#6]
I do an other class who can be used using the light extension system of Saxon, just by using the "java:" namespace mechanism. Using this, you don't need to develop a Java class to integrate the extension in the Saxon engine. 
You can integrate the source in you project to give this possibility too.
The source isn't complete, only the use of an uri for xquery is done

`xmlns:ext-mm="java:com.mmconsultants.marklogicsaxon.ConnectML"`

using :
database connection
`<xsl:variable name="connectML" select="ext-mm:new('ip', 'port', 'name', 'pwd')"/>`
xquery call :
`<xsl:variable name="res1" select="ext-mm:getQueryUri($connectML, $uri1)"/>`
and a second one  :
`xsl:variable name="res2" select="ext-mm:getQueryUri($connectML, $uri2)"/>`

Here is the Java source of the class :
`/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mmconsultants.marklogicsaxon;

import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.eval.EvalResultIterator;
import com.marklogic.client.eval.ServerEvaluationCall;
import com.marklogic.client.io.Format;
import com.marklogic.client.io.InputStreamHandle;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import net.sf.saxon.lib.StandardUnparsedTextResolver;
import org.apache.commons.io.input.ReaderInputStream;
import net.sf.saxon.om.LazySequence;
import fr.askjadev.xml.extfunctions.marklogic.result.MarkLogicSequenceIterator;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.net.URISyntaxException;
import net.sf.saxon.expr.XPathContext;
import net.sf.saxon.s9api.DocumentBuilder;
import net.sf.saxon.s9api.Processor;

/**
 *
 * @author marcl
 */
public class ConnectML {

    private Connection dataBaseConnection;

    public ConnectML(String host, String port, String username, String password) {
        System.err.println("constructeur avec 1 argument");
        dataBaseConnection = new Connection(host, port, username, password);
    }

    public Connection getConnection() {
        return dataBaseConnection;
    }

    static public LazySequence getQueryUri(XPathContext xpc, ConnectML connection, String uri) {
        System.err.println("URI: " + uri);
        Processor proc = new Processor(xpc.getConfiguration());
        DocumentBuilder builder = proc.newDocumentBuilder();
        DatabaseClient session = connection.getConnection().getDatabaseClient();
        URI queryUriResolved;
        try {
            queryUriResolved = new URI(uri);

            try {
                // Logger.getLogger(AbstractMLExtensionFunction.class.getName()).log(Level.INFO, queryUriResolved.toString());
                // Try to detect early when the URL points to nothing -> otherwise there can be a NullPointerException raised by StandardUnparsedTextResolver.connect()
                if (queryUriResolved.toURL().openConnection().getInputStream() == null) {
                    //throw new IOException("File not found: " + queryUriResolved.toString());
                    System.err.println("File not found: " + queryUriResolved.toString());
                }
            } catch (IOException ex) {
                System.err.println("File not found: " + queryUriResolved.toString());
                return null;
            }
            System.err.println("File found: " + queryUriResolved.toString());
            StandardUnparsedTextResolver unparsedTextResolver = new StandardUnparsedTextResolver();
            InputStreamHandle xquery = new InputStreamHandle(new ReaderInputStream(new FileReader(new File(queryUriResolved)), "UTF-8"));
            xquery.setFormat(Format.TEXT);

            System.err.println("getTest 2");
            ServerEvaluationCall call = session.newServerEval();
            // ajout de la xquery
            call.xquery(xquery);
            xquery.close();
            //       call = var.addToCall(callajout de varaibles externes
            System.err.println("appel eval");
            EvalResultIterator result = call.eval();
            System.err.println("fin eval");
            MarkLogicSequenceIterator it = new MarkLogicSequenceIterator(result, builder, xpc, session);
            System.err.println("fin analyse");
            return new LazySequence(it);

        } catch (URISyntaxException ex) {
            System.err.println("URI incorrecte 1: " + uri);
            return null;
        } catch (FileNotFoundException ex) {
            System.err.println("URI not found 1: " + uri);
            return null;
        }
    }

    private class Connection {

        private DatabaseClient client;

        public Connection(String host, String port, String username, String password) {
            Processor proc = new Processor(true);
            DocumentBuilder builder = proc.newDocumentBuilder();
            client = DatabaseClientFactory.newClient(host, 8003, username, password, DatabaseClientFactory.Authentication.DIGEST);
        }

        public DatabaseClient getDatabaseClient() {
            return client;
        }
    }
}
`

**Comment by AxelCourt** [comment]
Voir la branche **reflexiveExtensionFunction** + la release **1.2-RC1**.
