### ISSUE TITLE
Add the binary type

### ISSUE THREAD

**Issue by Marc95** [AxelCourt/saxon-marklogic-ext#7]
Hi axel,
Is it possible to add the BINARY type in the EvalResultConverter class?
I propose to convert the binary to BASE64_BINARY to be able to read it from XSL :

            if (evalResult.getType().equals(EvalResult.Type.BINARY)) {                
                byte[] r = evalResult.getAs(byte[].class);
                String e = java.util.Base64.getEncoder().encodeToString(r);
                return new XdmAtomicValue(e, ItemType.BASE64_BINARY);
            }

**Comment by AxelCourt** [comment]
Voir la branche reflexiveExtensionFunction + la release **1.2-RC2**.
