### ISSUE TITLE
Extension writes XQuery Results to tmp file

### ISSUE THREAD

**Issue by cmarchand** [AxelCourt/saxon-marklogic-ext#9]
Following [JIRA-SIETRAINMQ-503](https://jira.els-gestion.eu/browse/SIETRAINMQ-503), response from ML seems to be serialized on disk. It's a performance issue, and it may lead to I/O errors when tmp directory / filesystem is full.

**Comment by AxelCourt** [comment]
This should no longer be the case starting with MarkLogic Java Client API 4.0.2.
They changed their HTTP library for OkHttp which seems not to write temporary files after the HTTP request (see the changelog: https://github.com/marklogic/java-client-api/blob/master/CHANGELOG.md#402).

I don't see any temporary file being written with 4.2.0 version of the client, which is the one supported by this plugin right now. So you should be fine if this is the version you use in your project.
